# coding=utf-8


INI_FILE = """
# This is the template generated by csv2td
# Please replace <item> with actual values

# Teradata DSN
[<DSN>]
# Teradata logon
username: <username>
# Teradata logon password
password: <password>
# Schema name you have write access
default_database: <databasename>
# First n lines to guess the date type (max: 10,000)
max_lines: <number>
"""

FASTLOAD_CTL = """
"""
