# coding=utf-8

INI_FILE_KEYS = [
 	'db_url',
	'username',
	'password',
	'default_database',
	'max_lines_for_guess'
]


INI_FILE_NAME = 'csv2td.ini'


INI_FILE = """
# This is the template generated by csv2td
# Please replace <item> with actual values

# Teradata DSN
[<DSN>]
""" + '\n'.join('{v}: <{v}>'.format(v=x) for x in INI_FILE_KEYS)

FASTLOAD_CTL = """
SESSIONS 4;
errlimit 1000;
LOGON {dburl}/{username}, {password};


-- *************************************************************************************************************
DELETE FROM {schema}.{tablename};
SET RECORD VARTEXT ','  NOSTOP;

DEFINE
	  Process_Date  (VARCHAR(10))
	, Trx_Number    (VARCHAR(3))
	, Cust_Z_Num    (VARCHAR(8))
	, CisKey        (VARCHAR(11))
	, Attr_Name     (VARCHAR(200))
    , Attr_Value    (VARCHAR(2000))
FILE={csv_file_name}.csv;
SHOW;

BEGIN LOADING {schema}.{tablename} ERRORFILES {schema}.{tablename}_E1, {schema}.{tablename}_E2;
INSERT INTO {schema}.{tablename} VALUES (
	  :Process_Date (DATE, FORMAT 'YYYY-MM-DD')
	, :Trx_Number
	, :Cust_Z_Num
	, :CisKey
	, :Attr_Name
    , :Attr_Value
);

END LOADING;
LOGOFF
"""
